#:schema ../extra/schemas/icon-theme.json

[icon-theme]
name = "Lapce Codicons"

[icon-theme.ui]
"logo" = "lapce_logo.svg"
"menu" = "menu.svg"
"error" = "error.svg"
"add" = "add.svg"
"close" = "close.svg"
"unsaved" = "circle-filled.svg"
"warning" = "warning.svg"
"settings" = "settings-gear.svg"
"terminal" = "terminal.svg"
"keyboard" = "keyboard.svg"
"breadcrumb_separator" = "chevron-right.svg"
"symbol_color" = "symbol-color.svg"

"window.close" = "chrome-close.svg"
"window.restore" = "chrome-restore.svg"
"window.maximize" = "chrome-maximize.svg"
"window.minimize" = "chrome-minimize.svg"

"file" = "file.svg"
"file_explorer" = "files.svg"


"scm.icon" = "source-control.svg"
"scm.diff.modified" = "diff-modified.svg"
"scm.diff.added" = "diff-added.svg"
"scm.diff.removed" = "diff-removed.svg"
"scm.diff.renamed" = "diff-renamed.svg"

"palette.menu" = "chevron-down.svg"

"fold" = "fold.svg"
"fold.up" = "fold-up.svg"
"fold.down" = "fold-down.svg"

"dropdown.arrow" = "chevron-down.svg"

"panel.fold-down" = "chevron-down.svg"
"panel.fold-up" = "chevron-right.svg"

"location.forward" = "arrow-right.svg"
"location.backward" = "arrow-left.svg"

"item.opened" = "chevron-down.svg"
"item.closed" = "chevron-right.svg"

"directory.closed" = "folder.svg"
"directory.opened" = "folder-opened.svg"


"split.horizontal" = "split-horizontal.svg"

"tab.previous" = "chevron-left.svg"
"tab.next" = "chevron-right.svg"

"sidebar.left.on" = "layout-sidebar-left.svg"
"sidebar.left.off" = "layout-sidebar-left-off.svg"
"sidebar.right.on" = "layout-sidebar-right.svg"
"sidebar.right.off" = "layout-sidebar-right-off.svg"

"layout.panel.on" = "layout-panel.svg"
"layout.panel.off" = "layout-panel-off.svg"

"search.icon" = "search.svg"
"search.forward" = "arrow-down.svg"
"search.backward" = "arrow-up.svg"
"search.case_sensitive" = "case-sensitive.svg"
"search.whole_word" = "whole-word.svg"
"search.regex" = "regex.svg"
"search.replace" = "replace.svg"
"search.replace_all" = "replace-all.svg"



[icon-theme.foldername]

[icon-theme.filename]

[icon-theme.extension]
