[package]
name         = "texas-proxy"
license      = { workspace = true }
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }

[dependencies]
alacritty_terminal = { workspace = true }
anyhow             = { workspace = true }
crossbeam-channel  = { workspace = true }
directories        = { workspace = true }
dunce              = { workspace = true }
git2               = { workspace = true }
indexmap           = { workspace = true }
notify             = { workspace = true }
reqwest            = { workspace = true }
parking_lot        = { workspace = true }
regex              = { workspace = true }
tracing            = { workspace = true }
url                = { workspace = true }

lapce-xi-rope  = { workspace = true }
texas-rpc      = { workspace = true }

polling = "3.5.0"

# deleting files
trash = "3.0.6"

# search
ignore        = "0.4"
grep-searcher = "0.1"
grep-matcher  = "0.1"
grep-regex    = "0.1"
