name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - Cargo.toml
      - Cargo.lock
      - texas-**
      - .github/workflows/ci.yml
      - rust-toolchain.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  checks:
    name: Rust checks on Windows
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v5

      - name: Update toolchain and install components
        run: |
          rustup update --no-self-update
          rustup component add rustfmt clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Build
        run: cargo build --frozen --bin texas

      - name: Run tests
        run: cargo test --workspace
